---
title: "R Notebook"
output: html_notebook
---

```{r}
# Load necessary libraries
library(readxl)

# Read the flavors of cacao. Xlsx into the dfCacao data frame
dfCacao <- read_excel("flavors_of_cacao.xlsx")

#Display information about the dataset
cat("Number of rows:", nrow(dfCacao), "\n")
cat("Number of columns:", ncol(dfCacao), "\n")
cat("Column names:", names(dfCacao), "\n")
cat("Data types:", sapply(dfCacao, class), "\n")
```

```{r}
# Sort the dataset descending based on Ratings
dfCacaoSorted <- dfCacao[order(-dfCacao$Rating), ]
dfCacaoSorted
```
```{r}
# Count records in Portugal, Spain, Germany, and USA
dfPortugal <- subset(dfCacao, CompanyLocation == "Portugal")
dfSpain <- subset(dfCacao, CompanyLocation == "Spain")
dfGermany <- subset(dfCacao, CompanyLocation == "Germany")
dfUSA <- subset(dfCacao, CompanyLocation == "U.S.A.")
```

```{r}
# Count records in Switzerland in 2010 with a rating of 3.5
dfSwitzerland2010 <- subset(dfCacao, CompanyLocation == "Switzerland" & ReviewDate == 2010 & Rating == 3.5)
```

```{r}
# Store records of above countries in separate data frames and compare average ratings
avgRatingPortugal <- mean(dfPortugal$Rating)
avgRatingSpain <- mean(dfSpain$Rating)
avgRatingGermany <- mean(dfGermany$Rating)
avgRatingUSA <- mean(dfUSA$Rating)
```

```{r}
# Store all generated dataframes in excel format

library(readxl)
library(openxlsx)

write.xlsx(dfCacao, "dfCacao.xlsx", row.names = FALSE)
write.xlsx(dfCacaoSorted, "dfCacaoSorted.xlsx", row.names = FALSE)
write.xlsx(dfPortugal, "dfPortugal.xlsx", row.names = FALSE)
write.xlsx(dfSpain, "dfSpain.xlsx", row.names = FALSE)
write.xlsx(dfGermany, "dfGermany.xlsx", row.names = FALSE)
write.xlsx(dfUSA, "dfUSA.xlsx", row.names = FALSE)
write.xlsx(dfSwitzerland2010, "dfSwitzerland2010.xlsx", row.names = FALSE)
```
```{r}
# Display average ratings for comparison
cat("Average Rating in Portugal:", avgRatingPortugal, "\n")
cat("Average Rating in Spain:", avgRatingSpain, "\n")
cat("Average Rating in Germany:", avgRatingGermany, "\n")
cat("Average Rating in USA:", avgRatingUSA, "\n")
```

