---
title: "R Notebook"
output: html_notebook
---

```{r}


library(readxl)

file_path <- "Singapore Airbnb - Raw.xlsx"

data <- read_excel(file_path)

num_rows <- dim(data)[1]
num_cols <- dim(data)[2]

column_names <- colnames(data)

cat("Number of rows:", num_rows, "\n")
cat("Number of columns:", num_cols, "\n")
cat("Column names:", paste(column_names, collapse = ", "), "\n")

```
```{r}
missing_values <- colSums(is.na(data))

print("Number of missing values in each column:")
print(missing_values)
```
```{r}
# Identificar e remover elementos duplicados
duplicated_rows <- duplicated(data)
data_without_duplicates <- data[!duplicated_rows, ]

cat("Number of duplicate rows removed:", sum(duplicated_rows), "\n")

data_without_duplicates <- data.frame(data_without_duplicates, row.names = NULL)

cat("Number of rows after removing duplicates:", nrow(data_without_duplicates), "\n")
cat("Number of columns:", ncol(data_without_duplicates), "\n")
```

```{r}

for (col in names(data)) {
  if (is.numeric(data[[col]])) {
    boxplot(data[[col]], main = paste("Boxplot of", col), ylab = col)
  }
}
```
```{r}

```

